version: '3.7'

services:
  csvToMongoDB:
    build:
      context: .
      dockerfile: Dockerfile
    image: csvtomongodb:latest
    container_name: csvToMongoDB
    restart: always
    ports:
      - "8085:80"
