version: '3.8'

services:
  csvToMongoDB:
    build:
      context: .
      dockerfile: Dockerfile
    image: csvtomongodb
    container_name: csvToMongoDB
    hostname: csvToMongoDB
    restart: always
    ports:
      - "8088:80"
